version: '3.7'
services:
  pubchem-elastic:
    build:
      context: .
      args:
        OPEN_DISTRO_VERSION: ${OPEN_DISTRO_VERSION}
    image: odfe:${OPEN_DISTRO_VERSION}
    container_name: pubchem-elastic-node1
    environment:
      - node.name=pubchem-elastic-node1
      - cluster.name=pubchem-odfe-cluster
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - opendistro_security.disabled=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.initial_master_nodes=pubchem-elastic-node1
      - discovery.seed_hosts=pubchem-elastic-node1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./pubchem-odfe-data1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - pubchem-net

volumes:
  pubchem-odfe-data1:

networks:
  pubchem-net:
